### ISSUE TITLE
Testing Resources

### ISSUE THREAD

**Issue by nasainsbury** [JiscSD/web-accessibility-101#2]
On the [Testing Resources](https://github.com/JiscSD/web-accessibility-101/blob/main/9-testing-resources/README.md) page, there are some useful links.

There are quite a few links, and not sure which one is recommended. Can you write/find some resources on what `Automated` you would recommend etc?

**Comment by CarlyRich** [comment]
great suggestion! Also something that @Josh-Ring-jisc mentioned in the Accessibility drop in. I will add some more information 😃

**Comment by CarlyRich** [comment]
also @zzcgulm may want to add some of the information from his confluence page in the future 😃
